### PR TITLE
port CI changes

### PR DESCRIPTION
**Pull request by adrian-kong**
ports decoupled CI changes to v4.0.13 which is released at 
https://www.swiftnav.com/resource-library?product=Swift+Console&category=Installer&release=Latest&search=Swift+Console&filters=no&title=Swift+Console

### CODE REVIEW

**Comment by silverjam** [comment]
Do we need the Cargo.lock changes?

**Comment by adrian-kong** [comment]
> Do we need the Cargo.lock changes?

maybe not but since the main issue is sysinfo/ntapi not being updated maybe just keep

**Comment by silverjam** [comment]
Should this be merged into this branch? https://github.com/swift-nav/swift-toolbox/tree/swift-toolbox-v4.0.0-branch

**Comment by adrian-kong** [comment]
> Should this be merged into this branch? https://github.com/swift-nav/swift-toolbox/tree/swift-toolbox-v4.0.0-branch

both branches are identical
oh didn't realize there already is a branch for that. 👍

**Review by silverjam — COMMENTED** [review]
Assuming there are changes to the CI repo that we'll need too?  Do we need to branch the CI repo?

**Comment by adrian-kong** [comment]
> Assuming there are changes to the CI repo that we'll need too? Do we need to branch the CI repo?

yep we do, currently here:
https://github.com/swift-nav/swift-toolbox-ci/pull/11

there are some issues with mac signing which looks odd 🤔 
https://github.com/swift-nav/swift-toolbox-ci/actions/runs/4933517260/jobs/8818076340
other than that it seems like it would release just fine

**Comment by adrian-kong** [comment]
https://github.com/swift-nav/swift-toolbox/releases/tag/v4.1.11
release was successful after retry

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/4942368822)

**Comment by silverjam** [comment]
oops, didn't mean to close the PR

**Review by silverjam — APPROVED** [review]
feel free to merge once we're able to get CI passing cleanly

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/4942523945)

**Comment by silverjam** [comment]
Decoupled CI is working, just taking a bit longer, I think we adjust the timeout to 45 minutes it should pass cleanly: https://github.com/swift-nav/swift-toolbox-ci/actions/runs/4942658545

**Pull request merged**
