### PR TITLE
Add publish step to swift-toolbox in CI/CD

### PR DESCRIPTION
**Pull request by pcrumley**
This PR adds a command to the Makefile which aids in publishing of the binary tools in console_backend.

### CODE REVIEW

**Review by adrian-kong — COMMENTED** [review]
1 - yea, just a simple release tag
2 - for releases that already exist on package registry, you would probably need to create a external script to fetch all previous gh release and generate based on that.
3 - not too sure about value but no harm in adding all the binaries @silverjam

also should this be done on the private CI side where releases are created (and just add an extra step to build additional binaries and hook to package registry) https://github.com/swift-nav/swift-toolbox-ci/blob/ed55ef50a99e661845a0c9527d9430191831f86a/.github/workflows/distribute.yml#L52

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/6168533629)

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/6178832397)

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/6179265397)

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/6179464128)

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/6179639034)

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/6180755877)

**Comment by silverjam** [comment]
> also should this be done on the private CI side where releases are created (and just add an extra step to build additional binaries and hook to package registry) https://github.com/swift-nav/swift-toolbox-ci/blob/ed55ef50a99e661845a0c9527d9430191831f86a/.github/workflows/distribute.yml#L52

Doing this in https://github.com/swift-nav/swift-toolbox-ci could work, but it's not necessary since we don't need to use any of the lab machines

**Comment by silverjam** [comment]
> > also should this be done on the private CI side where releases are created (and just add an extra step to build additional binaries and hook to package registry) https://github.com/swift-nav/swift-toolbox-ci/blob/ed55ef50a99e661845a0c9527d9430191831f86a/.github/workflows/distribute.yml#L52
> 
> Doing this in https://github.com/swift-nav/swift-toolbox-ci could work, but it's not necessary since we don't need to use any of the lab machines

Also, we'd have to introduce new architectures into the matrix there anyway, so I think it's a bit cleaner to just do the Swift Toolbox CLI stuff in it's own CI workflow.

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/6202079272)

**Comment by pcrumley** [comment]
I simplified this PR to just contain the makefile changes necessary to make this happen. The CI/CD will live elsewhere.

**Review by silverjam — APPROVED** [review]

**Pull request merged**
