### PR TITLE
[backport] fixed aspect ratio in charts [CPP-939]

### PR DESCRIPTION
**Pull request by adrian-kong**
https://github.com/swift-nav/swift-toolbox/pull/911

### CODE REVIEW

**Review by silverjam — APPROVED** [review]

**Comment by pcrumley** [comment]
did we change the linter on this code? if it is failing here do we need to port the lint fixes to the latest version? I'm just confused about the delta here.

**Comment by adrian-kong** [comment]
> did we change the linter on this code? if it is failing here do we need to port the lint fixes to the latest version? I'm just confused about the delta here.

just old qt things 😪

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/5009461680)

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/5009553407)

**Pull request merged**
