### PR TITLE
event based recording status [CPP-843]

### PR DESCRIPTION
**Pull request by adrian-kong**
removes logging thread, send smaller packets of changes,
defers the full state to the frontend.
we can also refactor this into the event receivers that was introduced in instant filter updates etc... 

downside is we send whenever we receive a frame meaning it would be dependent on the stream of info - which we can do some batching if this happen (too many updates for frontend gui => laggy ?)

this is also to prepare for another ticket - record empty streams of data

### CODE REVIEW

**Comment by adrian-kong** [comment]
> Failing code quality checks, what else is remaining for this PR?

was working on other tickets this will need to go back into WIP from the received reviews

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/3869643346)

**Comment by adrian-kong** [comment]
all behaviours as mentioned should be resolved now 👍

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/3898806087)

**Comment by adrian-kong** [comment]
will need to merge this in before re-releasing. (addresses some bugs & improvements, test if notarytool works)

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/3926189935)

**Review by ziwift — APPROVED** [review]
lgtm

**Pull request merged**
