### PR TITLE
cleanup some reusable methods and less lines

### PR DESCRIPTION
**Pull request by adrian-kong**
a pr to do some refactoring stuff

### CODE REVIEW

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/3880661706)

**Comment by adrian-kong** [comment]
@pcrumley maybe can merge this to your branch #890 as code cleanup

**Comment by swiftnav-travis** [comment]
Frontend and Release Workflow Started [here](https://github.com/swift-nav/toolbox-backend-ci/actions/runs/3889475722)

**Review by silverjam — APPROVED** [review]

**Comment by pcrumley** [comment]
@adrian-kong 

I am happy to merge my code cleanup PR but it hasn't been approved yet. It is pretty low risk though.

**Pull request merged**
