### PR TITLE
[v4.0] update deps, add TdkIcm42670, baudrate to enum dropdown [DIP-247]

### PR DESCRIPTION
**Pull request by adrian-kong**
adds tdkicm42670
baudrate enum dropdown
update deps

for 4.0 version

### CODE REVIEW

**Review by pcrumley — COMMENTED** [review]
do you have any idea why the memtest is failing? my guess is it is in the update deps stuff, since the other stuff looks pretty innocuous. I think you should break out the dependency updates because it seems unrelated to the logic changes.

**Comment by pcrumley** [comment]
it looks like mimalloc bump is the reason this is failing see: https://github.com/swift-nav/swift-toolbox/pull/1161

**Comment by silverjam** [comment]
Please revert Cargo.lock -- dependencies should remain static for officially released builds.  We need a full test cycle (including manual tests) to fully validate dependencies.

**Comment by silverjam** [comment]
> Please revert Cargo.lock -- dependencies should remain static for officially released builds.  We need a full test cycle (including manual tests) to fully validate dependencies.

The changes to sbp and sbp-settings are fine, since they are our own dependencies.

**Review by silverjam — APPROVED** [review]

**Comment by silverjam** [comment]
Please make sure to forward port this to the main branch

**Comment by adrian-kong** [comment]
> Please make sure to forward port this to the main branch

these changes were missing from v4.0 branch only - main branchuses updated version of chrono

**Pull request merged**
