### PR TITLE
use switch cases

### PR DESCRIPTION
**Pull request by adrian-kong**

### CODE REVIEW

**Comment by adrian-kong** [comment]
using this branch on solution pos
Screenshot 2023-04-03 at 9 39 18 am

using silverjam/py311
Screenshot 2023-04-03 at 9 44 13 am

seems like switch is slower (?)
might be better readability but not really i guess. can disregard this change

**Comment by adrian-kong** [comment]
#1002

**Comment by silverjam** [comment]
Maybe a diction lookup to some functions would be faster?

**Comment by adrian-kong** [comment]
hmm yea maybe - was hoping the python bump can use some cool match statements but nvm.
might be too tiny to measure performance changes on if elses to using map lookups, will just close this PR :(

**Pull request closed without merging**
